server:
  port: 8080
  servlet:
    context-path: /

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      pathMapping:
        health: /health-check
      basePath: /
endpoint:
  auth: "http://localhost:8884/api/v1/auth"